### ISSUE TITLE
Halifax (CYHZ)

### ISSUE THREAD

**Issue by GoldenXLence** [vStrips/HoldingPoint-Stands#13]

**Comment by jackkoskie** [comment]
[Halifax (CYHZ).zip](https://github.com/vStrips/HoldingPoint-Stands/files/6292197/Halifax.CYHZ.zip)

**Comment by jackkoskie** [comment]
[Gates.txt](https://github.com/vStrips/HoldingPoint-Stands/files/6297031/Gates.txt)

**Comment by MattM09** [comment]
Committed to 1.17.

**Comment by jackkoskie** [comment]
[Holding Point.zip](https://github.com/vStrips/HoldingPoint-Stands/files/7998608/Holding.Point.zip)

Updated Taxiways @MattM09
