### ISSUE TITLE
Oslo Gardermoen (ENGM)

### ISSUE THREAD

**Issue by morettio** [vStrips/HoldingPoint-Stands#2]

**Comment by morettio** [comment]
[ox.zip](https://github.com/vStrips/HoldingPoint-Stands/files/5961471/ox.zip)

**Comment by fcooper94** [comment]
Hello Morettio,

Good job, thank you for your time this afternoon. 

I have a few things we would require you to amend please before we approve the files.

1. For the Holding Point diagram, Some of the holding points are too small. Could you use the large icons for all of them?
2. For the Holding Point diagram, could you trim the image so we have less excess background.#
3. Could you make sure that only HOLDING POINTS are marked not TAXIWAYS. For example, P1 and not the full 'P' taxiway.
4. For the Stand diagram, Could you please remove the 'Parking/Taxiways' under 'View' in ADE. We just want the yellow taxiway line if possible.
5. For the Stand diagram also, could you please increase the size of the yellow stand box and use the large template to make it easier to use for a touch-screen user. 
6. Please make sure the stand boxes are not too close to each-other.
7. Could you change the folder structure please to 'E-N-GM'

You will need to remap the image using the indexer.

Thank you again for your contribution,

Fraser

(Please email the changes to datasubmission@vstrips.co.uk (.zip format is ideal)

**Comment by morettio** [comment]
The Holding poing chart, do I need to use a background fram AES? Or can i
make a layout my self (like EGLL)?


*Jakob Arne Brønstad*

*Tlf: (+47) 986 50 540*


ons. 10. feb. 2021 kl. 22:49 skrev Fraser Cooper <notifications@github.com>:

**Comment by MattM09** [comment]
You can do what you feel best Jakob, however, we would ask you keep continuity with other airfields.

**Comment by morettio** [comment]
Here is the file with all the fixes that Fraser talked about.

I can't remove the green lines on Stand map, the taxiways is green at our side.

Hope this helps :)

Jakob Arne Brønstad
Tlf: (+47) 986 50 540


tor. 11. feb. 2021 kl. 01:04 skrev Matt Middleton <notifications@github.com>:

**Comment by morettio** [comment]
"Could you make sure that only HOLDING POINTS are marked not TAXIWAYS.
For example, P1 and not the full 'P' taxiway."

This is not done in Norway. We use the whole taxiway as a hold short point.

Jakob Arne Brønstad
Tlf: (+47) 986 50 540

tor. 11. feb. 2021 kl. 01:14 skrev Jakob Arne Brønstad <jakobregi@gmail.com>:

**Comment by MattM09** [comment]
Once you're happy, email the zip file to datasubmission@vstrips.co.uk.
