### ISSUE TITLE
London Heathrow (EGLL)

### ISSUE THREAD

**Issue by fcooper94** [vStrips/HoldingPoint-Stands#3]
Updated both CAT I and CAT III holding point layouts. (Now 90% in-line with IRL layout).

- Still using a combination of AIR + GMC layout.
- Possible split into individual layouts in the future. 

![LL_CAT_1](https://user-images.githubusercontent.com/16825107/107887459-341d0e00-6efe-11eb-8272-56005a1b4428.jpg)
![LL_CAT_3](https://user-images.githubusercontent.com/16825107/107887461-34b5a480-6efe-11eb-909e-f322b0a35f9f.jpg)

Updates uploaded to dropbox.

**Comment by MattM09** [comment]
Committed to 1.15.
